# Generated by Django 5.1.2 on 2024-11-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
